<a href="https://colab.research.google.com/github/Akskyash/SE101/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from sklearn import tree
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [65]:
path ='/content/survey_num_testdrive.csv'
dataset = pd.read_csv(path)

In [66]:
dataset

,Q1 gender,Q2 from,Q1 ADDICTED RATE,Q4 feel addicted,Q5 red or watery e1 after taking drug?,Q6 sleep properly,Q7 weight change,Q8 mood swings,Q9 financial difficulties,Q10 diseases,...,Q15 losing interest,Q16 isolating,Q17 FAMILY RELATION,Q18 eat foods,Q19 reaction slowed,Q20 physical symptoms,Q21 body,Q22 reaction body,Q24 doctor,Q25 Rate mental health
0,1,1,2,"1, 2, 5",1,2,1,3,2,1,...,3,1,3,2,2,1,1,"2, 3, 5, 8",4,2
1,1,1,1,5,1,2,2,3,2,2,...,2,2,3,2,2,1,3,8,4,2
2,1,1,1,5,1,2,2,2,2,2,...,2,2,3,1,2,1,3,9,4,1
3,1,1,1,3,2,2,2,3,3,2,...,2,2,3,2,2,1,3,9,4,4
4,1,1,1,6,1,2,2,2,2,2,...,2,2,3,3,1,1,3,9,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,1,1,2,"1, 2, 3, 4, 5",1,2,1,1,1,1,...,1,1,1,2,1,1,1,"1, 2, 3, 4, 5, 6, 7, 8, 16",1,5
298,1,1,2,"1, 2, 3, 4, 5",1,2,1,1,1,1,...,1,1,1,2,1,1,1,"1, 2, 3, 4, 5, 6, 7, 8, 16",1,5
299,1,1,2,"1, 2, 3, 4, 5",1,2,1,1,1,1,...,1,1,1,2,1,1,1,"1, 2, 3, 4, 5, 6, 7, 8, 16",1,5
300,1,1,2,"1, 2, 3, 4, 5",1,2,1,1,1,1,...,1,1,1,2,1,1,1,"1, 2, 3, 4, 5, 6, 7, 8, 16",1,5
301,1,1,2,"1, 2, 3, 4, 5",1,2,1,1,1,1,...,1,1,1,2,1,1,1,"1, 2, 3, 4, 5, 6, 7, 8, 16",1,5

In [67]:
type(dataset)

pandas.core.frame.DataFrame

In [68]:
print(dataset.columns)

Index(['Q1 gender', 'Q2 from', 'Q1 ADDICTED RATE', 'Q4 feel addicted',
       'Q5 red or watery e1 after taking drug?', 'Q6 sleep properly',
       'Q7 weight change', 'Q8 mood swings', ' Q9 financial difficulties',
       'Q10 diseases', 'Q11 disease type', 'Q12 harm yourself',
       'Q13 difficulty  personal relationships ',
       ' Q14 Neglect responsibilities', 'Q15 losing interest',
       ' Q16 isolating  ', 'Q17 FAMILY RELATION', 'Q18 eat foods',
       'Q19 reaction slowed', 'Q20 physical symptoms ', 'Q21 body',
       'Q22 reaction body', 'Q24 doctor ', 'Q25 Rate  mental health'],
      dtype='object')

In [69]:
attribut = ['Q1 gender', 'Q2 from', 'Q1 ADDICTED RATE', 'Q4 feel addicted',
       'Q5 red or watery e1 after taking drug?', 'Q6 sleep properly',
       'Q7 weight change', 'Q8 mood swings', ' Q9 financial difficulties',
       'Q10 diseases', 'Q11 disease type', 'Q12 harm yourself',
       'Q13 difficulty  personal relationships ',
       ' Q14 Neglect responsibilities', 'Q15 losing interest',
       ' Q16 isolating  ', 'Q17 FAMILY RELATION', 'Q18 eat foods',
       'Q19 reaction slowed', 'Q20 physical symptoms ', 'Q21 body',
       'Q22 reaction body', 'Q24 doctor ']

In [70]:
data = dataset.loc[:, attribut]
target = dataset['Q25 Rate  mental health']

In [71]:
dataTraining, dataTesting, targetTraining, targetTesting = train_test_split(data, target, test_size=0.2)

In [72]:
modeldata = tree.DecisionTreeClassifier(criterion='entropy')
modeldata = modeldata.fit(dataTraining, targetTraining)

ValueError: ignored

In [ ]:
plt.subplots(figsize=(20,20))
tree.plot_tree(modeldata, feature names = attribut, class_names = modeldata.classes_, filled = True, fontsize=12)

# New Section